import SideNav from "@/app/ui/sidenav"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by create next app",
}

export default function DocLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
            <div className="w-full flex-none md:w-64">
                <SideNav />
            </div>
            <div className="grow overflow-y-auto md:p-12">{children}</div>
        </div>
    )
}