// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Gallery': typeof import("../components/Gallery.vue")['default'],
    'Item': typeof import("../components/Item.vue")['default'],
    'Preview': typeof import("../components/Preview.vue")['default'],
    'Tab': typeof import("../components/Tab.vue")['default'],
    'CommentForm': typeof import("../components/comment/Form.vue")['default'],
    'CommentItem': typeof import("../components/comment/Item.vue")['default'],
    'LayoutAside': typeof import("../components/layout/Aside.vue")['default'],
    'LayoutDrawer': typeof import("../components/layout/Drawer.vue")['default'],
    'LayoutFooter': typeof import("../components/layout/Footer.vue")['default'],
    'LayoutHeader': typeof import("../components/layout/Header.vue")['default'],
    'LayoutLogo': typeof import("../components/layout/Logo.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyGallery': typeof import("../components/Gallery.vue")['default'],
    'LazyItem': typeof import("../components/Item.vue")['default'],
    'LazyPreview': typeof import("../components/Preview.vue")['default'],
    'LazyTab': typeof import("../components/Tab.vue")['default'],
    'LazyCommentForm': typeof import("../components/comment/Form.vue")['default'],
    'LazyCommentItem': typeof import("../components/comment/Item.vue")['default'],
    'LazyLayoutAside': typeof import("../components/layout/Aside.vue")['default'],
    'LazyLayoutDrawer': typeof import("../components/layout/Drawer.vue")['default'],
    'LazyLayoutFooter': typeof import("../components/layout/Footer.vue")['default'],
    'LazyLayoutHeader': typeof import("../components/layout/Header.vue")['default'],
    'LazyLayoutLogo': typeof import("../components/layout/Logo.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const Gallery: typeof import("../components/Gallery.vue")['default']
export const Item: typeof import("../components/Item.vue")['default']
export const Preview: typeof import("../components/Preview.vue")['default']
export const Tab: typeof import("../components/Tab.vue")['default']
export const CommentForm: typeof import("../components/comment/Form.vue")['default']
export const CommentItem: typeof import("../components/comment/Item.vue")['default']
export const LayoutAside: typeof import("../components/layout/Aside.vue")['default']
export const LayoutDrawer: typeof import("../components/layout/Drawer.vue")['default']
export const LayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LayoutHeader: typeof import("../components/layout/Header.vue")['default']
export const LayoutLogo: typeof import("../components/layout/Logo.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyGallery: typeof import("../components/Gallery.vue")['default']
export const LazyItem: typeof import("../components/Item.vue")['default']
export const LazyPreview: typeof import("../components/Preview.vue")['default']
export const LazyTab: typeof import("../components/Tab.vue")['default']
export const LazyCommentForm: typeof import("../components/comment/Form.vue")['default']
export const LazyCommentItem: typeof import("../components/comment/Item.vue")['default']
export const LazyLayoutAside: typeof import("../components/layout/Aside.vue")['default']
export const LazyLayoutDrawer: typeof import("../components/layout/Drawer.vue")['default']
export const LazyLayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LazyLayoutHeader: typeof import("../components/layout/Header.vue")['default']
export const LazyLayoutLogo: typeof import("../components/layout/Logo.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
